<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/24
 * Time: 14:12
 */

namespace App\Bean;


use EasySwoole\Core\Component\Spl\SplBean;

class BaseBean extends SplBean
{
    /**
     * @var int
     */
    protected $createtime;

    /**
     * @var int
     */
    protected $updatetime;

    public function initialize(): void
    {
        empty($this->createtime) && $this->createtime = time();
        empty($this->updatetime) && $this->updatetime = time();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return int
     */
    public function getCreatetime(): ?int
    {
        return $this->createtime;
    }

    /**
     * @param int $createtime
     */
    public function setCreatetime(?int $createtime): void
    {
        $this->createtime = $createtime;
    }

    /**
     * @return int
     */
    public function getUpdatetime(): ?int
    {
        return $this->updatetime;
    }

    /**
     * @param int $updatetime
     */
    public function setUpdatetime(?int $updatetime): void
    {
        $this->updatetime = $updatetime;
    }


}